%{
note: calculation of the stator field generated by a 3-phase distributed winding
%}

% initialization
clc;
clear;
close all;
addpath(genpath('C:\emdlab-win64'));

% dimensions & parameters
gv_ISD = 74;
gv_OSD = 125;
gv_Lstk = 70;
gv_gap = 0.5;
gv_Dsh = 30;
gv_Ns = 36;
gv_wst = 3;
gv_dss = 15;
gv_Ntc = 85;
gv_Iph = 1.9;

% define geometry data base
g = emdlab_g2d_db;

% add geometry from library
emdlab_g2d_lib_tc15(g, gv_ISD, gv_OSD, gv_Ns, gv_dss, gv_wst, 'stator', 'sc');
g.addFace('rotor', g.addAnnularSectorLoop(gv_Dsh/2,gv_ISD/2-gv_gap,0,pi/6));
g.setFaceColor('rotor',200,200,200);

% setting the wireframe mesh by mesh size function
f_mesh = @(r) interp1([gv_Dsh/2,gv_ISD/2-gv_gap,gv_OSD/2], [4,gv_gap,3], r, 'linear','extrap');
g.setMeshLengthByRadialFunction(f_mesh);

% mesh generation
m = g.generateMesh('mg0');

% add materials
m.addMaterial('m530', emdlab_mlib_es_M530_50A);
m.addMaterial('copper', emdlab_mlib_copper);

% set materials
m.setMaterial('rotor','m530');
m.setMaterial('stator','m530');
m.setMaterial('sc','copper');

% generate full mesh
m.aux_cmxjcrj('rotor',6)
m.aux_cmxjcrj('stator',gv_Ns)
m.aux_cmxjcr('sc',gv_Ns)

% add circular air gap
m.aux_addCircularAirGap('ag',0,0,gv_ISD/2-gv_gap,0,0,gv_ISD/2,2);

% getting an instance of solver object
s = emdlab_solvers_ms2d_tl6_ihnl(m);
s.setLengthUnit('mm');
s.setDepth(gv_Lstk);

% define windings
s.defineCoil('phaseA');
s.defineCoil('phaseB');
s.defineCoil('phaseC');
pA = [1,2,3,10,11,12]; pA = [pA, pA+18];
ntc = gv_Ntc*[-1,-1,-1,1,1,1]; ntc = [ntc,ntc];
pB = pA + 6;
pC = pA + 3;
s.addMeshZones2Coil('phaseA', 'sc' + string(pA), ntc, 0.15);
s.addMeshZones2Coil('phaseB', 'sc' + string(pB), ntc, 0.15);
s.addMeshZones2Coil('phaseC', 'sc' + string(pC), -ntc, 0.15);

% set phase currents
s.setCoilCurrent('phaseA', gv_Iph*1.41);
s.setCoilCurrent('phaseB', -gv_Iph*1.41/2);
s.setCoilCurrent('phaseC', -gv_Iph*1.41/2);

% apply boundary conditions: zero vector potential on all boundary nodes
s.setAzBC(m.getfbn, 0);

% run solver
s.solve;

% visualize solution
s.gui;
s.plotBrBtOnCircle(0, 0, gv_ISD/2-gv_gap/2, 1000);